# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from pathlib import Path
import json
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

filename = path = Path(__file__).parent / "usecaseData_full.json"

dataTest = []
nameTest = []
def dataForTest():
    global dataTest, nameTest
    with open(filename, "r") as f:
        data = json.load(f)
        for key, values in data.items():
            print(key)
            url = values["url"]
            loginCredential = values["loginCredential"]
            eventName = values["eventName"]
            startTime = values["startTime"]
            extend = values["extend"]
            eventDescription = values["eventDescription"]
            eventLocation = values["eventLocation"]
            durationSelection = values["durationSelection"]
            repeat = values["repeat"]
            expectedResult = values["expectResult"]
            dataTest.append(
                (url, loginCredential, eventName, startTime,
                 extend, eventDescription, eventLocation,
                 durationSelection, repeat,
                 expectedResult)
            )
            nameTest.append(key)
    return dataTest


def getElementValue(element):
    return element["value"]


class TestUsecase1():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(10)
        self.driver.set_page_load_timeout(3000)
        self.vars = {}
        self.exception = False

    def teardown_method(self, method):
        self.driver.quit()
        pass

    """
    Save effort when finding element, assuming all element object has "findMethod" and "findString" attribute.
    findMethod: By.??
    findString: a string to find element, depend on the findMethod.
    """
    def findElementShort(self, element):
        return self.driver.find_element(By.get_finder(element["findMethod"]), element["findString"])

    """
    get element value, assuming each element have "value" attribute
    """

    @pytest.mark.parametrize(
        "url, "
        "loginCredential, "  # (username, password)
        "eventName, "
        "startTime, "  # (day, month, year, hour, minute)
        "extend, "  # (yes, no)
        "eventDescription, "
        "eventLocation, "
        "durationSelection, "  # (0: no duration, 1: until, 2: in minutes) 
        "repeat, "  # (yes, no)
        "expectedResult, ",
        dataForTest(),
        ids=nameTest
    )
    def test_usecase1(self, url, loginCredential, eventName, startTime, extend,
                      eventDescription, eventLocation, durationSelection,
                      repeat,
                      expectedResult):
        self.driver.get(url)
        self.driver.set_window_size(1274, 757)
        self.driver.find_element(By.CSS_SELECTOR, ".login > a").click()
        time.sleep(3)
        self.findElementShort(loginCredential["username"]).clear()
        self.findElementShort(loginCredential["password"]).clear()
        self.findElementShort(loginCredential["username"]).send_keys(getElementValue(loginCredential["username"]))
        self.findElementShort(loginCredential["password"]).send_keys(getElementValue(loginCredential["password"]))

        self.driver.find_element(By.CSS_SELECTOR, ".login-container").click()
        self.driver.find_element(By.ID, "loginbtn").click()
        time.sleep(3)       #page transition wait
        self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
        time.sleep(2)       #page transition wait

        self.vars["month"] = self.driver.find_element(By.CSS_SELECTOR, ".current:nth-child(3)").text
        if self.driver.execute_script("return (arguments[0] != \"November 2024\")", self.vars["month"]):
            assert self.driver.find_element(By.CSS_SELECTOR, ".arrow_text:nth-child(2)").text == "November"
            self.driver.find_element(By.CSS_SELECTOR, ".arrow_text:nth-child(2)").click()
            time.sleep(1)

        self.driver.find_element(By.XPATH, "//button[contains(.,\'New event\')]").click()
        self.findElementShort(eventName).send_keys(getElementValue(eventName))

        self.findElementShort(startTime["day"]).click()
        dropdown = self.findElementShort(startTime["day"])
        dropdown.find_element(By.XPATH, f".//option[. = '{getElementValue(startTime["day"])}']").click()

        self.findElementShort(startTime["month"]).click()
        dropdown = self.findElementShort(startTime["month"])
        dropdown.find_element(By.XPATH, f".//option[. = '{getElementValue(startTime["month"])}']").click()

        self.findElementShort(startTime["year"]).click()
        dropdown = self.findElementShort(startTime["year"])
        dropdown.find_element(By.XPATH, f".//option[. = '{getElementValue(startTime["year"])}']").click()

        self.findElementShort(startTime["hour"]).click()
        dropdown = self.findElementShort(startTime["hour"])
        ##get elements from parent element using XPATH
        ##NOTE: in order to utilize XPATH from current element, you must add "." to beginning of path
        dropdown.find_element(By.XPATH, f".//option[. = '{getElementValue(startTime["hour"])}']").click()

        self.findElementShort(startTime["minute"]).click()
        dropdown = self.findElementShort(startTime["minute"])
        dropdown.find_element(By.XPATH, f".//option[. = '{getElementValue(startTime["minute"])}']").click()
        if eval(getElementValue(extend)):
            self.findElementShort(extend).click()
            time.sleep(3)
            # access data in a iframe: https://stackoverflow.com/questions/52045083/how-to-get-attribute-src-from-iframe-in-iframe-using-selenium
            self.driver.switch_to.frame(eventDescription["frameName"])
            element = self.findElementShort(eventDescription)
            self.driver.execute_script(
                "if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '" + getElementValue(eventDescription) + "'}",
                element)
            time.sleep(1)
            self.driver.switch_to.default_content()

            self.findElementShort(eventLocation).send_keys(getElementValue(eventLocation))
            self.driver.find_element(By.get_finder(durationSelection["findMethod"]),
                                     f"{durationSelection["findString"]}{getElementValue(durationSelection)}").click()

            if getElementValue(durationSelection) == "1":
                self.findElementShort(durationSelection["durationUntil"]["day"]).click()
                dropdown = self.findElementShort(durationSelection["durationUntil"]["day"])
                dropdown.find_element(
                    By.XPATH, f".//option[. = '{getElementValue(durationSelection["durationUntil"]["day"])}']").click()

                self.findElementShort(durationSelection["durationUntil"]["month"]).click()
                dropdown = self.findElementShort(durationSelection["durationUntil"]["month"])
                dropdown.find_element(
                    By.XPATH, f".//option[. = '{getElementValue(durationSelection["durationUntil"]["month"])}']").click()

                self.findElementShort(durationSelection["durationUntil"]["year"]).click()
                dropdown = self.findElementShort(durationSelection["durationUntil"]["year"])
                dropdown.find_element(
                    By.XPATH, f".//option[. = '{getElementValue(durationSelection["durationUntil"]["year"])}']").click()

                self.findElementShort(durationSelection["durationUntil"]["hour"]).click()
                dropdown = self.findElementShort(durationSelection["durationUntil"]["hour"])
                dropdown.find_element(
                    By.XPATH, f".//option[. = '{getElementValue(durationSelection["durationUntil"]["hour"])}']").click()

                self.findElementShort(durationSelection["durationUntil"]["minute"]).click()
                dropdown = self.findElementShort(durationSelection["durationUntil"]["minute"])
                dropdown.find_element(
                    By.XPATH, f".//option[. = '{getElementValue(durationSelection["durationUntil"]["minute"])}']").click()

            elif getElementValue(durationSelection) == "2":

                self.findElementShort(durationSelection["durationMinutes"]).click()
                self.findElementShort(durationSelection["durationMinutes"]).send_keys(
                    getElementValue(durationSelection["durationMinutes"]))
            if eval(getElementValue(repeat)):

                self.findElementShort(repeat).click()
                # self.driver.find_element(By.ID, "fitem_id_repeats").click()
                self.findElementShort(repeat["noOfRepeat"]).clear()
                self.findElementShort(repeat["noOfRepeat"]).send_keys(getElementValue(repeat["noOfRepeat"]))
        self.driver.find_element(By.XPATH, "//button[contains(.,\'Save\')]").click()
        time.sleep(1)

        if eventName == "":
            assert (self.findElementShort(expectedResult["expectedError"]).text ==
                    getElementValue(expectedResult["expectedError"]))
            self.exception = True

        if (eval(getElementValue(extend)) and
                getElementValue(durationSelection) == "1" and
                getElementValue(startTime["day"]) > getElementValue(durationSelection["durationUntil"]["day"])):
            time.sleep(3)
            assert (self.findElementShort(expectedResult["expectedError"]).text ==
                    getElementValue(expectedResult["expectedError"]))
            self.exception = True
            self.findElementShort(durationSelection["durationUntil"]["day"]).click()
            dropdown = self.findElementShort(durationSelection["durationUntil"]["day"])
            dropdown.find_element(
                By.XPATH, f".//option[. = '{getElementValue(startTime["day"])}']").click()

        if not self.exception:
            self.driver.find_element(By.CSS_SELECTOR, ".eventname").click()
            # self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(1) > .col-11").click()
            time.sleep(2)
            assert (self.findElementShort(expectedResult["expectedTime"]).text ==
                    getElementValue(expectedResult["expectedTime"]).replace("Â", ""))
            if eval(getElementValue(extend)):
                if getElementValue(expectedResult["expectedDescription"]) != "":
                    assert (self.findElementShort(expectedResult["expectedDescription"]).text ==
                            getElementValue(expectedResult["expectedDescription"]))
                if getElementValue(expectedResult["expectedLocation"]) != "":
                    assert (self.findElementShort(expectedResult["expectedLocation"]).text ==
                            getElementValue(expectedResult["expectedLocation"]))
            time.sleep(1)
            self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button").click()
            time.sleep(1)
            if not eval(getElementValue(repeat)):
                delButton = self.driver.find_element(By.XPATH, "//button[contains(.,\'Delete event\')]")
                delButton.click()
                time.sleep(1)
            else:
                delButton = self.driver.find_element(By.XPATH, "//button[contains(.,\'Delete this event\')]")
                delButton.click()

                time.sleep(3)
                # delete second event:
                self.driver.find_element(By.XPATH, "//tr[4]/td[2]/div/div/ul/li/a/span[2]").click()
                time.sleep(2)
                assert (self.findElementShort(expectedResult["expectedTime2"]).text ==
                        getElementValue(expectedResult["expectedTime2"]).replace("Â", ""))
                if eval(getElementValue(extend)):
                    if getElementValue(expectedResult["expectedDescription"]) != "":
                        assert (self.findElementShort(expectedResult["expectedDescription"]).text ==
                                getElementValue(expectedResult["expectedDescription"]))
                    if getElementValue(expectedResult["expectedLocation"]) != "":
                        assert (self.findElementShort(expectedResult["expectedLocation"]).text ==
                                getElementValue(expectedResult["expectedLocation"]))
                time.sleep(2)       # to find the damn button
                delButton = self.driver.find_element(By.XPATH, ".//div[2]/div/div/div[3]/button")
                delButton.click()
                time.sleep(1)
                delButton2 = self.driver.find_element(By.XPATH, "//button[contains(.,\'Delete event\')]")
                delButton2.click()

        else:       # exception = True
            self.driver.find_element(By.ID, "id_name").click()
            self.driver.find_element(By.ID, "id_name").clear()
            self.driver.find_element(By.ID, "id_name").send_keys("exception")
            time.sleep(3)
            exButton = self.driver.find_element(By.XPATH, "//button[contains(.,'Save')]")
            exButton.click()
            if exButton.is_displayed():
                exButton.click()
            time.sleep(1)
            self.driver.find_element(By.XPATH, "//span[contains(.,\'exception\')]").click()
            time.sleep(2)
            self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button").click()
            time.sleep(1)
            delButton = self.driver.find_element(By.XPATH, "//button[contains(.,\'Delete event\')]")
            delButton.click()

        #log out
        time.sleep(3)
        self.driver.find_element(By.ID, "user-menu-toggle").click()
        self.driver.find_element(By.XPATH, "//a[contains(.,\'Log out\')]").click()
